import { createHash, randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';
import { HARD_CONTEXT_LIMITS, boundedInteger } from '../context/budgets.js';
import { contextRoot, readRepositoryText, redactRepositoryText, repositoryFiles, repositorySource, safeRepositoryFile } from '../context/repository.js';
import { findSymbols } from '../context/symbols.js';
import { contextPacksDirectory, atomicJson } from '../execution/home.js';
import { gitProvenance } from '../execution/evidence.js';
import { repositoryIdentity } from '../execution/trust/repository-identity.js';
import { git } from '../lib/git.js';
import { diagnoseLog } from './diagnose-log.js';
import { failure } from './common.js';

const budgetSchema=z.object({maxFiles:z.number().int().min(1).max(HARD_CONTEXT_LIMITS.maxFiles).optional(),maxLines:z.number().int().min(1).max(HARD_CONTEXT_LIMITS.maxLines).optional(),maxBytes:z.number().int().min(1).max(HARD_CONTEXT_LIMITS.maxBytes).optional()}).optional();
const seedSchema=z.object({executionId:z.string().regex(/^exec_[A-Za-z0-9_-]{8,200}$/).optional(),files:z.array(z.string()).max(HARD_CONTEXT_LIMITS.maxFiles).optional(),symbols:z.array(z.string().min(1).max(200)).max(HARD_CONTEXT_LIMITS.maxFiles).optional()}).optional();
export const contextPackInput=z.object({path:z.string().optional(),objective:z.string().min(1).max(1000),budget:budgetSchema,seedEvidence:seedSchema});
const reasonSchema=z.object({code:z.enum(['explicit_file','explicit_symbol','stack_reference','git_diff','exact_text']),evidence:z.string().optional(),source:z.string().optional()});
const itemSchema=z.object({type:z.enum(['file_slice','symbol','diagnostic_reference','diff_file','text_match']),file:z.string(),symbol:z.string().optional(),startLine:z.number().int(),endLine:z.number().int(),content:z.string(),bytes:z.number().int(),sha256:z.string(),reason:reasonSchema,source:z.object({type:z.literal('repository_file'),trust:z.literal('untrusted_content')}),redacted:z.boolean()});
export const contextPackOutput=z.object({status:z.enum(['complete','partial','error']),contextPackId:z.string().optional(),objective:z.string().optional(),repository:z.object({root:z.string(),sha:z.string().optional(),branch:z.string().optional(),dirty:z.boolean(),dirtyFileCount:z.number().int()}).optional(),budget:z.object({maxFiles:z.number().int(),maxLines:z.number().int(),maxBytes:z.number().int()}).optional(),usage:z.object({files:z.number().int(),lines:z.number().int(),bytes:z.number().int()}).optional(),items:z.array(itemSchema).optional(),excluded:z.object({ignoredFiles:z.number().int(),candidateItems:z.number().int(),budgetExcludedItems:z.number().int()}).optional(),metrics:z.object({repositoryFiles:z.number().int(),candidateFiles:z.number().int(),includedFiles:z.number().int(),candidateLines:z.number().int(),includedLines:z.number().int(),candidateBytes:z.number().int(),includedBytes:z.number().int(),budgetUtilization:z.object({filesPercent:z.number(),linesPercent:z.number(),bytesPercent:z.number()})}).optional(),truncated:z.boolean().optional(),confidence:z.enum(['high','medium','unknown']).optional(),manifestPath:z.string().optional(),errorCode:z.string().optional(),message:z.string().optional()});
export const contextPackAnnotations={readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false} as const;

interface Candidate{type:'file_slice'|'symbol'|'diagnostic_reference'|'diff_file'|'text_match';file:string;startLine:number;endLine:number;symbol?:string;rank:number;reason:z.infer<typeof reasonSchema>}
const digest=(value:string)=>`sha256:${createHash('sha256').update(value).digest('hex')}`;
const percent=(used:number,limit:number)=>Math.round((used/limit)*10_000)/100;

export async function contextPack(input:z.infer<typeof contextPackInput>){try{
  const root=await contextRoot(input.path);if(!root.gitRepository)throw new Error('CONTEXT_PACK_REQUIRES_GIT_REPOSITORY');
  const budget={maxFiles:boundedInteger(input.budget?.maxFiles,8,HARD_CONTEXT_LIMITS.maxFiles,'max_files'),maxLines:boundedInteger(input.budget?.maxLines,1200,HARD_CONTEXT_LIMITS.maxLines,'max_lines'),maxBytes:boundedInteger(input.budget?.maxBytes,75_000,HARD_CONTEXT_LIMITS.maxBytes,'max_bytes')};
  const listing=await repositoryFiles(root.repositoryRoot,true),candidates:Candidate[]=[];
  for(const file of input.seedEvidence?.files??[]){const target=await safeRepositoryFile(root.repositoryRoot,file),content=await readRepositoryText(root.repositoryRoot,target.relative);candidates.push({type:'file_slice',file:target.relative,startLine:1,endLine:Math.min(200,content.text.split(/\r?\n/).length),rank:0,reason:{code:'explicit_file',source:target.relative}});}
  for(const symbol of input.seedEvidence?.symbols??[]){const found=await findSymbols(root.repositoryRoot,true,symbol,undefined,20);for(const item of found.symbols)candidates.push({type:'symbol',file:item.file,startLine:item.startLine,endLine:item.endLine,symbol,rank:0,reason:{code:'explicit_symbol',source:symbol}});}
  if(input.seedEvidence?.executionId){const diagnosis=await diagnoseLog({executionId:input.seedEvidence.executionId,maxFrames:20});if('relevantFrames'in diagnosis)for(const frame of diagnosis.relevantFrames??[]){const relative=path.isAbsolute(frame.file)?path.relative(root.repositoryRoot,frame.file).replaceAll('\\','/'):frame.file.replaceAll('\\','/');try{await safeRepositoryFile(root.repositoryRoot,relative);candidates.push({type:'diagnostic_reference',file:relative,startLine:Math.max(1,frame.line-15),endLine:frame.line+15,rank:1,reason:{code:'stack_reference',evidence:input.seedEvidence.executionId}});}catch{/* frame outside this repository */}}}
  const changed=await git(root.repositoryRoot,['diff','--name-only','HEAD','--']);if(changed.status==='completed')for(const file of changed.stdout.split(/\r?\n/).filter(Boolean).map((value)=>value.replaceAll('\\','/'))){try{const content=await readRepositoryText(root.repositoryRoot,file);candidates.push({type:'diff_file',file,startLine:1,endLine:Math.min(120,content.text.split(/\r?\n/).length),rank:2,reason:{code:'git_diff',source:'working_tree'}});}catch{/* deleted/binary */}}
  const terms=[...new Set(input.objective.match(/[A-Za-z_$][\w$]{3,}/g)??[])].filter((term)=>!['determine','investigate','where','what','with','from','that','this'].includes(term.toLowerCase())).slice(0,8);
  if(terms.length)for(const file of listing.files){try{const content=await readRepositoryText(root.repositoryRoot,file);const lines=content.text.split(/\r?\n/);for(let index=0;index<lines.length;index++)if(terms.some((term)=>lines[index].includes(term))){candidates.push({type:'text_match',file,startLine:Math.max(1,index-9),endLine:Math.min(lines.length,index+11),rank:3,reason:{code:'exact_text',source:terms.find((term)=>lines[index].includes(term))}});break;}}catch{/* skip */}}
  const unique=[...candidates.sort((a,b)=>a.rank-b.rank||a.file.localeCompare(b.file)||a.startLine-b.startLine).reduce((map,item)=>map.has(item.file)?map:map.set(item.file,item),new Map<string,Candidate>()).values()];
  let candidateLines=0,candidateBytes=0;for(const item of unique){try{const content=await readRepositoryText(root.repositoryRoot,item.file);const selected=content.text.split(/\r?\n/).slice(item.startLine-1,item.endLine).join('\n');candidateLines+=selected.split(/\r?\n/).length;candidateBytes+=Buffer.byteLength(selected);}catch{/* skip */}}
  const items:any[]=[];let usedLines=0,usedBytes=0,budgetExcludedItems=0;
  for(const candidate of unique){if(items.length>=budget.maxFiles||usedLines>=budget.maxLines||usedBytes>=budget.maxBytes){budgetExcludedItems++;continue;}try{const content=await readRepositoryText(root.repositoryRoot,candidate.file),lines=content.text.split(/\r?\n/),end=Math.min(candidate.endLine,candidate.startLine+(budget.maxLines-usedLines)-1,lines.length),raw=lines.slice(candidate.startLine-1,end).map((line,index)=>`${candidate.startLine+index}: ${line}`).join('\n'),remaining=budget.maxBytes-usedBytes,safe=redactRepositoryText(raw),buffer=Buffer.from(safe.text),bounded=buffer.subarray(0,remaining).toString('utf8'),actualLines=bounded?bounded.split(/\r?\n/).length:0;if(!bounded){budgetExcludedItems++;continue;}const bytes=Buffer.byteLength(bounded);items.push({type:candidate.type,file:candidate.file,...(candidate.symbol?{symbol:candidate.symbol}:{}),startLine:candidate.startLine,endLine:end,content:bounded,bytes,sha256:digest(raw),reason:candidate.reason,source:repositorySource,redacted:safe.redacted});usedLines+=actualLines;usedBytes+=bytes;if(buffer.byteLength>remaining)budgetExcludedItems++;}catch{budgetExcludedItems++;}}
  const provenance=await gitProvenance(root.repositoryRoot),identity=await repositoryIdentity(root.repositoryRoot),contextPackId=`ctx_${Date.now().toString(36)}_${randomUUID()}`,directory=path.join(contextPacksDirectory(),identity.repositoryId,contextPackId),manifestPath=path.join(directory,'manifest.json'),usage={files:new Set(items.map((item)=>item.file)).size,lines:usedLines,bytes:usedBytes},truncated=budgetExcludedItems>0||listing.truncated,confidence=items.some((item)=>['explicit_file','explicit_symbol','stack_reference'].includes(item.reason.code))?'high' as const:items.length?'medium' as const:'unknown' as const;
  const metrics={repositoryFiles:listing.files.length,candidateFiles:unique.length,includedFiles:usage.files,candidateLines,includedLines:usage.lines,candidateBytes,includedBytes:usage.bytes,budgetUtilization:{filesPercent:percent(usage.files,budget.maxFiles),linesPercent:percent(usage.lines,budget.maxLines),bytesPercent:percent(usage.bytes,budget.maxBytes)}};
  const manifest={contextPackId,objective:input.objective,repository:{root:root.repositoryRoot,...provenance},budget,usage,items:items.map((item)=>Object.fromEntries(Object.entries(item).filter(([key])=>key!=='content'))),excluded:{ignoredFiles:listing.ignoredFiles,candidateItems:unique.length,budgetExcludedItems},metrics,truncated,confidence};await mkdir(directory,{recursive:true});await atomicJson(manifestPath,manifest);
  return{status:truncated?'partial' as const:'complete' as const,...manifest,items,manifestPath};
}catch(error){return failure(error,'CONTEXT_PACK_FAILED');}}
