import { z } from 'zod';
import { boundedInteger } from '../context/budgets.js';
import { safeRepositoryFile } from '../context/repository.js';
import { boundedGraph, confidenceOf, methodsOf, repositoryModel, structuralEdges } from '../architecture/graph.js';
import { HARD_GRAPH_LIMITS, edgeSchema, fileId, nodeSchema, provenanceSchema, staticBoundary, staticBoundarySchema, symbolId, type GraphEdge, type GraphNode } from '../architecture/model.js';
import { failure } from './common.js';

export const dependencyGraphInput = z.object({ path: z.string().optional(), scope: z.object({ type: z.enum(['repository','workspace','file','symbol']), value: z.string().max(500).optional() }).optional(), depth: z.number().int().min(1).max(HARD_GRAPH_LIMITS.maxDepth).optional(), maxNodes: z.number().int().min(1).max(HARD_GRAPH_LIMITS.maxNodes).optional(), maxEdges: z.number().int().min(1).max(HARD_GRAPH_LIMITS.maxEdges).optional() });
export const dependencyGraphOutput = z.object({ status: z.enum(['complete','partial','error']), repositoryRoot: z.string().optional(), repository: provenanceSchema.optional(), scope: z.object({ type: z.string(), value: z.string().optional(), seeds: z.array(z.string()) }).optional(), nodes: z.array(nodeSchema).optional(), edges: z.array(edgeSchema).optional(), depthReached: z.number().int().optional(), returnedNodes: z.number().int().optional(), totalKnownNodes: z.number().int().optional(), returnedEdges: z.number().int().optional(), totalKnownEdges: z.number().int().optional(), sourceFiles: z.number().int().optional(), analyzedFiles: z.number().int().optional(), unresolvedImports: z.number().int().optional(), truncated: z.boolean().optional(), resolution: z.object({ methods: z.array(z.string()), confidence: z.enum(['high','medium','low','unknown']) }).optional(), boundary: staticBoundarySchema.optional(), errorCode: z.string().optional(), message: z.string().optional() });

export async function dependencyGraph(input: z.infer<typeof dependencyGraphInput>) {
  try {
    const model = await repositoryModel(input.path), scope = input.scope ?? { type: 'repository' as const }, limits = { depth: boundedInteger(input.depth, 3, HARD_GRAPH_LIMITS.maxDepth, 'depth'), maxNodes: boundedInteger(input.maxNodes, 200, HARD_GRAPH_LIMITS.maxNodes, 'max_nodes'), maxEdges: boundedInteger(input.maxEdges, 600, HARD_GRAPH_LIMITS.maxEdges, 'max_edges') };
    const { nodes, edges } = structuralEdges(model); let seeds: string[] = [];
    const priority: Record<string, number> = { repository: 0, package: 1, file: 2, external_package: 3, symbol: 4 };
    if (scope.type === 'repository') seeds = [...nodes.values()].sort((a, b) => (priority[a.type] ?? 9) - (priority[b.type] ?? 9) || a.id.localeCompare(b.id)).map((node) => node.id);
    else if (scope.type === 'workspace') { if (!scope.value) throw new Error('SCOPE_VALUE_REQUIRED'); const pkg = model.packages.find((candidate) => candidate.directory === scope.value!.replace(/\/$/, '') || candidate.name === scope.value || candidate.id === scope.value); if (!pkg) throw new Error('WORKSPACE_NOT_FOUND'); seeds = [pkg.id, ...[...model.modules.values()].filter((module) => module.package === pkg.id).map((module) => fileId(module.file))]; }
    else if (scope.type === 'file') { if (!scope.value) throw new Error('SCOPE_VALUE_REQUIRED'); const target = await safeRepositoryFile(model.root, scope.value); if (!nodes.has(fileId(target.relative))) throw new Error('SCOPE_FILE_NOT_ANALYZED'); seeds = [fileId(target.relative)]; }
    else { if (!scope.value) throw new Error('SCOPE_VALUE_REQUIRED'); const definitions = [...model.modules.values()].flatMap((module) => module.symbols.filter((symbol) => symbol.symbol === scope.value).map((symbol) => ({ module, symbol }))); if (!definitions.length) throw new Error('SYMBOL_NOT_FOUND'); const ambiguous = definitions.length > 1;
      for (const { module, symbol } of definitions) { const id = symbolId(module.file, symbol.symbol); if (!nodes.has(id)) nodes.set(id, { id, type: 'symbol', name: symbol.symbol, file: module.file, package: module.package, language: module.language } satisfies GraphNode); seeds.push(id);
        let references = 0; for (const other of model.modules.values()) { if (other.file === module.file || references >= 200 || (ambiguous && !other.imports.some((record) => record.resolved === module.file && record.names.includes(symbol.symbol)))) continue; const index = other.text.split(/\r?\n/).findIndex((line) => new RegExp(`\\b${symbol.symbol.replace(/[$]/g, '\\$&')}\\b`).test(line)); if (index >= 0) { references++; edges.push({ from: fileId(other.file), to: id, relationship: 'references', evidence: { file: other.file, line: index + 1, method: 'textual_reference' }, classification: 'inferred', resolutionMethod: 'textual', confidence: 'low' } satisfies GraphEdge); } } } }
    const graph = boundedGraph(nodes, edges, seeds, limits), unresolvedImports = [...model.modules.values()].reduce((sum, module) => sum + module.imports.filter((record) => record.unresolved).length, 0), truncated = graph.truncated || model.truncated;
    return { status: truncated ? 'partial' as const : 'complete' as const, repositoryRoot: model.root, repository: model.provenance, scope: { type: scope.type, ...(scope.value ? { value: scope.value } : {}), seeds: seeds.slice(0, 50) }, nodes: graph.nodes, edges: graph.edges, depthReached: graph.depthReached, returnedNodes: graph.returnedNodes, totalKnownNodes: graph.totalKnownNodes, returnedEdges: graph.returnedEdges, totalKnownEdges: graph.totalKnownEdges, sourceFiles: model.sourceFileCount, analyzedFiles: model.modules.size, unresolvedImports, truncated, resolution: { methods: methodsOf(graph.edges), confidence: confidenceOf(graph.edges) }, boundary: staticBoundary };
  } catch (error) { return failure(error, 'DEPENDENCY_GRAPH_FAILED'); }
}
