import { z } from 'zod';
import { readExecutionLogs } from '../context/execution-evidence.js';
import { redactString } from '../lib/redaction.js';
import { failure } from './common.js';

export const diagnoseLogInput=z.object({executionId:z.string().regex(/^exec_[A-Za-z0-9_-]{8,200}$/),maxFrames:z.number().int().min(1).max(50).optional()});
const frame=z.object({file:z.string(),line:z.number().int(),column:z.number().int().optional(),text:z.string()});
export const diagnoseLogOutput=z.object({status:z.enum(['complete','partial','error']),executionId:z.string().optional(),primaryFailure:z.object({type:z.string(),message:z.string()}).optional(),failingTest:z.object({name:z.string(),file:z.string().optional(),line:z.number().int().optional()}).optional(),causedBy:z.array(z.object({type:z.string(),message:z.string(),file:z.string().optional(),line:z.number().int().optional()})).optional(),relevantFrames:z.array(frame).optional(),confidence:z.enum(['medium','low','unknown']).optional(),truncated:z.boolean().optional(),source:z.object({type:z.literal('execution_log'),trust:z.literal('untrusted_content')}).optional(),errorCode:z.string().optional(),message:z.string().optional()});
const normalize=(value:string)=>value.replaceAll('\\','/');
export async function diagnoseLog(input:z.infer<typeof diagnoseLogInput>){try{const logs=await readExecutionLogs(input.executionId),text=`${logs.stdout}\n${logs.stderr}`,lines=text.split(/\r?\n/),frames:any[]=[];let primary:any,failingTest:any;const causedBy:any[]=[];for(const line of lines){let match=/FAILED\s+([^\s:]+(?:::\S+)*)\s+-\s+(.+)/.exec(line);if(match)failingTest={name:match[1],file:match[1].split('::')[0]};match=/\b([A-Za-z_][\w.]*(?:Error|Exception|Failure)|AssertionError):\s*(.+)/.exec(line);if(match)primary={type:match[1],message:redactString(match[2].slice(0,500))};match=/Caused by:\s*([A-Za-z_][\w.]*(?:Error|Exception))(?::\s*(.*))?/.exec(line);if(match)causedBy.push({type:match[1],message:redactString((match[2]??'').slice(0,500))});const patterns=[/\bat\s+.*?\(?([^()\s]+\.[A-Za-z]+):(\d+):(\d+)\)?/,/File\s+["']([^"']+)["'],\s+line\s+(\d+)/,/([^\s:]+\.[A-Za-z]+)\((\d+),(\d+)\):\s+error\b/i,/([^\s:]+\.[A-Za-z]+):(\d+):(\d+)\s+error\b/i];for(const pattern of patterns){const hit=pattern.exec(line);if(hit&&frames.length<(input.maxFrames??10)){frames.push({file:normalize(hit[1]),line:Number(hit[2]),...(hit[3]?{column:Number(hit[3])}:{}),text:redactString(line.trim().slice(0,500))});break;}}}if(!primary){const meaningful=[...lines].reverse().find((line)=>/\b(?:error|failed|failure|exception)\b/i.test(line));if(meaningful)primary={type:'Error',message:redactString(meaningful.trim().slice(0,500))};}const confidence=primary||failingTest||frames.length?'medium' as const:text.trim()?'low' as const:'unknown' as const;return{status:logs.truncated?'partial' as const:'complete' as const,executionId:input.executionId,...(primary?{primaryFailure:primary}:{}),...(failingTest?{failingTest}:{}),causedBy,relevantFrames:frames,confidence,truncated:logs.truncated,source:{type:'execution_log' as const,trust:'untrusted_content' as const}};}catch(error){return failure(error,'DIAGNOSE_LOG_FAILED');}}
