import { z } from 'zod';
import { HARD_CONTEXT_LIMITS, boundedInteger } from '../context/budgets.js';
import { contextRoot, readRepositoryText, redactRepositoryText, repositoryFiles, repositorySource } from '../context/repository.js';
import { failure } from './common.js';

const referenceSchema=z.object({file:z.string(),line:z.number().int(),column:z.number().int(),context:z.string(),source:z.object({type:z.literal('repository_file'),trust:z.literal('untrusted_content')}),redacted:z.boolean()});
export const findReferencesInput=z.object({path:z.string().optional(),symbol:z.string().regex(/^[A-Za-z_$][\w$]*$/),definitionFile:z.string().optional(),maxResults:z.number().int().min(1).max(HARD_CONTEXT_LIMITS.maxReferences).optional()});
export const findReferencesOutput=z.object({status:z.enum(['complete','partial','error']),symbol:z.string().optional(),repositoryRoot:z.string().optional(),references:z.array(referenceSchema).optional(),resolutionMethod:z.literal('textual').optional(),confidence:z.literal('low').optional(),totalReferences:z.number().int().optional(),returnedReferences:z.number().int().optional(),scannedFiles:z.number().int().optional(),truncated:z.boolean().optional(),redactionCount:z.number().int().optional(),errorCode:z.string().optional(),message:z.string().optional()});
export async function findReferences(input:z.infer<typeof findReferencesInput>){try{const root=await contextRoot(input.path),limit=boundedInteger(input.maxResults,50,HARD_CONTEXT_LIMITS.maxReferences,'max_results'),listing=await repositoryFiles(root.repositoryRoot,root.gitRepository),regex=new RegExp(`\\b${input.symbol.replace(/[$]/g,'\\$&')}\\b`,'g'),references:any[]=[];let total=0,scannedFiles=0,redactionCount=0;for(const file of listing.files){try{const content=await readRepositoryText(root.repositoryRoot,file);scannedFiles++;for(const [index,line] of content.text.split(/\r?\n/).entries()){regex.lastIndex=0;for(let match=regex.exec(line);match;match=regex.exec(line)){total++;if(references.length<limit){const context=redactRepositoryText(line.slice(0,300));redactionCount+=context.redactionCount;references.push({file,line:index+1,column:match.index+1,context:context.text,source:repositorySource,redacted:context.redacted});}if(match[0].length===0)regex.lastIndex++;}}}catch{/* skip */}}const truncated=total>references.length||listing.truncated;return{status:truncated?'partial' as const:'complete' as const,symbol:input.symbol,repositoryRoot:root.repositoryRoot,references,resolutionMethod:'textual' as const,confidence:'low' as const,totalReferences:total,returnedReferences:references.length,scannedFiles,truncated,redactionCount};}catch(error){return failure(error,'FIND_REFERENCES_FAILED');}}
