import { z } from 'zod';
import { HARD_CONTEXT_LIMITS, boundedInteger } from '../context/budgets.js';
import { byteSlice, contextRoot, redactRepositoryText, repositorySource } from '../context/repository.js';
import { git } from '../lib/git.js';
import { failure } from './common.js';

const ref=z.string().regex(/^[A-Za-z0-9._/@{}~^-]+$/).max(200);
export const getDiffInput=z.object({path:z.string().optional(),mode:z.enum(['working_tree','staged','commit','range']),commit:ref.optional(),from:ref.optional(),to:ref.optional(),maxBytes:z.number().int().min(1).max(HARD_CONTEXT_LIMITS.maxDiffBytes).optional()});
const file=z.object({path:z.string(),status:z.string(),additions:z.number().int(),deletions:z.number().int()});
export const getDiffOutput=z.object({status:z.enum(['complete','partial','error']),mode:z.string().optional(),repositoryRoot:z.string().optional(),files:z.array(file).optional(),summary:z.object({filesChanged:z.number().int(),additions:z.number().int(),deletions:z.number().int()}).optional(),patch:z.string().optional(),bytes:z.number().int().optional(),truncated:z.boolean().optional(),redacted:z.boolean().optional(),redactionCount:z.number().int().optional(),source:z.object({type:z.literal('repository_file'),trust:z.literal('untrusted_content')}).optional(),errorCode:z.string().optional(),message:z.string().optional()});
function argumentsFor(input:z.infer<typeof getDiffInput>,format:'numstat'|'name-status'|'patch'){const extra=format==='numstat'?['--numstat']:format==='name-status'?['--name-status']:['--patch','--no-ext-diff'];if(input.mode==='working_tree')return['diff',...extra,'--'];if(input.mode==='staged')return['diff','--cached',...extra,'--'];if(input.mode==='commit'){if(!input.commit)throw new Error('COMMIT_REQUIRED');return['show','--format=',...extra,input.commit,'--'];}if(!input.from||!input.to)throw new Error('RANGE_REFS_REQUIRED');return['diff',...extra,input.from,input.to,'--'];}
export async function getDiff(input:z.infer<typeof getDiffInput>){try{const root=await contextRoot(input.path);if(!root.gitRepository)throw new Error('GIT_REPOSITORY_REQUIRED');const maxBytes=boundedInteger(input.maxBytes,75_000,HARD_CONTEXT_LIMITS.maxDiffBytes,'max_bytes'),[stats,names,patch]=await Promise.all([git(root.repositoryRoot,argumentsFor(input,'numstat')),git(root.repositoryRoot,argumentsFor(input,'name-status')),git(root.repositoryRoot,argumentsFor(input,'patch'),30_000)]);if([stats,names,patch].some((item)=>item.status!=='completed'))throw new Error('GIT_DIFF_FAILED');const counts=new Map<string,{additions:number;deletions:number}>();for(const line of stats.stdout.split(/\r?\n/)){const [a,d,...rest]=line.split('\t');if(!rest.length)continue;counts.set(rest.join('\t').replaceAll('\\','/'),{additions:Number(a)||0,deletions:Number(d)||0});}const files=names.stdout.split(/\r?\n/).filter(Boolean).map((line)=>{const [status,...rest]=line.split('\t'),file=rest.at(-1)?.replaceAll('\\','/')??'';return{path:file,status,additions:counts.get(file)?.additions??0,deletions:counts.get(file)?.deletions??0};});const safe=redactRepositoryText(patch.stdout),bounded=byteSlice(safe.text,maxBytes),additions=files.reduce((sum,item)=>sum+item.additions,0),deletions=files.reduce((sum,item)=>sum+item.deletions,0);return{status:bounded.truncated?'partial' as const:'complete' as const,mode:input.mode,repositoryRoot:root.repositoryRoot,files,summary:{filesChanged:files.length,additions,deletions},patch:bounded.value,bytes:Buffer.byteLength(bounded.value),truncated:bounded.truncated,redacted:safe.redacted,redactionCount:safe.redactionCount,source:repositorySource};}catch(error){return failure(error,'GET_DIFF_FAILED');}}
