import { z } from 'zod';
import { findSymbols } from '../context/symbols.js';
import { byteSlice, contextRoot, readRepositoryText, redactRepositoryText, repositorySource } from '../context/repository.js';
import { HARD_CONTEXT_LIMITS } from '../context/budgets.js';
import { failure } from './common.js';

const candidate=z.object({symbol:z.string(),kind:z.string(),file:z.string(),startLine:z.number().int(),endLine:z.number().int(),language:z.string(),resolutionMethod:z.string(),confidence:z.string()});
export const readSymbolInput=z.object({path:z.string().optional(),file:z.string().optional(),symbol:z.string().min(1).max(200)});
export const readSymbolOutput=z.object({status:z.enum(['complete','ambiguous','not_found','error']),repositoryRoot:z.string().optional(),symbol:z.string().optional(),kind:z.string().optional(),file:z.string().optional(),startLine:z.number().int().optional(),endLine:z.number().int().optional(),language:z.string().optional(),content:z.string().optional(),resolutionMethod:z.string().optional(),confidence:z.string().optional(),candidates:z.array(candidate).optional(),truncated:z.boolean().optional(),redacted:z.boolean().optional(),redactionCount:z.number().int().optional(),source:z.object({type:z.literal('repository_file'),trust:z.literal('untrusted_content')}).optional(),errorCode:z.string().optional(),message:z.string().optional()});
export async function readSymbol(input:z.infer<typeof readSymbolInput>){try{const root=await contextRoot(input.path),found=await findSymbols(root.repositoryRoot,root.gitRepository,input.symbol,undefined,HARD_CONTEXT_LIMITS.maxSearchResults),matches=input.file?found.symbols.filter((item)=>item.file.replaceAll('\\','/')===input.file!.replaceAll('\\','/')):found.symbols;if(!matches.length)return{status:'not_found' as const,repositoryRoot:root.repositoryRoot,symbol:input.symbol,candidates:[]};if(matches.length>1)return{status:'ambiguous' as const,repositoryRoot:root.repositoryRoot,symbol:input.symbol,candidates:matches};const item=matches[0],file=await readRepositoryText(root.repositoryRoot,item.file),raw=file.text.split(/\r?\n/).slice(item.startLine-1,item.endLine).map((line,index)=>`${item.startLine+index}: ${line}`).join('\n'),bounded=byteSlice(raw,HARD_CONTEXT_LIMITS.maxBytes),safe=redactRepositoryText(bounded.value);return{status:'complete' as const,repositoryRoot:root.repositoryRoot,...item,content:safe.text,truncated:bounded.truncated,redacted:safe.redacted,redactionCount:safe.redactionCount,source:repositorySource};}catch(error){return failure(error,'READ_SYMBOL_FAILED');}}
