import { mkdtemp, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import os from 'node:os'; import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { runProcess } from '../../src/lib/process-runner.js';
import { runCapability } from '../../src/tools/run-common.js';
import { approve } from '../../src/execution/trust/store.js';

let temp=''; let previousHome:string|undefined; let previousWorkspace:string|undefined;
afterEach(async()=>{if(temp)await rm(temp,{recursive:true,force:true}); if(previousHome===undefined)delete process.env.DEVBRAIN_HOME;else process.env.DEVBRAIN_HOME=previousHome;if(previousWorkspace===undefined)delete process.env.DEVBRAIN_WORKSPACE_ROOT;else process.env.DEVBRAIN_WORKSPACE_ROOT=previousWorkspace;});
async function repository(script:string){temp=await mkdtemp(path.join(os.tmpdir(),'devbrain-pipeline-'));const repo=path.join(temp,'repo'),home=path.join(temp,'home');await import('node:fs/promises').then(({mkdir})=>mkdir(repo));previousHome=process.env.DEVBRAIN_HOME;previousWorkspace=process.env.DEVBRAIN_WORKSPACE_ROOT;process.env.DEVBRAIN_HOME=home;process.env.DEVBRAIN_WORKSPACE_ROOT=temp;for(const args of [['init'],['config','user.email','test@example.com'],['config','user.name','Test']])await runProcess({executable:'git',args,cwd:repo});await writeFile(path.join(repo,'package.json'),JSON.stringify({scripts:{test:script},devDependencies:{vitest:'1'}}));await writeFile(path.join(repo,'package-lock.json'),'{}');await runProcess({executable:'git',args:['add','.'],cwd:repo});await runProcess({executable:'git',args:['commit','-m','fixture'],cwd:repo});return repo;}

describe('trusted execution pipeline',()=>{
  it('resolves a requested package below the canonical Git root',async()=>{temp=await mkdtemp(path.join(os.tmpdir(),'devbrain-subproject-'));const repo=path.join(temp,'repo'),project=path.join(repo,'app');const {mkdir}=await import('node:fs/promises');await mkdir(project,{recursive:true});previousHome=process.env.DEVBRAIN_HOME;previousWorkspace=process.env.DEVBRAIN_WORKSPACE_ROOT;process.env.DEVBRAIN_HOME=path.join(temp,'home');process.env.DEVBRAIN_WORKSPACE_ROOT=temp;for(const args of [['init'],['config','user.email','test@example.com'],['config','user.name','Test']])await runProcess({executable:'git',args,cwd:repo});await writeFile(path.join(project,'package.json'),JSON.stringify({scripts:{test:'node -e "console.log(\'Tests  1 passed\')"'},devDependencies:{vitest:'1'}}));await writeFile(path.join(project,'package-lock.json'),'{}');await runProcess({executable:'git',args:['add','.'],cwd:repo});await runProcess({executable:'git',args:['commit','-m','fixture'],cwd:repo});expect(await runCapability({path:project},'test')).toMatchObject({status:'approval_required',proposedInvocation:{cwd:await realpath(project)}});});
  it('does not execute before out-of-band approval',async()=>{const repo=await repository('node -e "require(\'fs\').writeFileSync(\'ran.txt\',\'yes\')"');const result=await runCapability({path:repo},'test');expect(result).toMatchObject({status:'approval_required',authorizationStatus:'approval_required',capability:'test'});await expect(readFile(path.join(repo,'ran.txt'),'utf8')).rejects.toThrow();});
  it('persists evidence and reports dirty provenance after CLI-layer approval',async()=>{const repo=await repository('node -e "console.log(\'Tests  1 passed\')"');const pending=await runCapability({path:repo},'test');if(!('approvalId' in pending)||!pending.approvalId)throw new Error('missing approval');await approve(pending.approvalId);await writeFile(path.join(repo,'dirty.txt'),'dirty');const result=await runCapability({path:repo},'test');expect(result).toMatchObject({status:'complete',authorizationStatus:'authorized',executionStatus:'completed',resultStatus:'passed',provenance:{git:{dirty:true,dirtyFileCount:1},log:{stdoutSha256:expect.stringMatching(/^sha256:/),stderrSha256:expect.stringMatching(/^sha256:/)}}});if(!('provenance' in result)||!result.provenance)throw new Error('missing provenance');await expect(readFile(result.provenance.log.stdoutPath,'utf8')).resolves.toContain('1 passed');await expect(readFile(result.provenance.log.stderrPath,'utf8')).resolves.toBe('');});
  it('reports an engineering failure as completed rather than a tool error',async()=>{const repo=await repository('node -e "console.log(\'Tests  1 failed\');process.exit(1)"');const pending=await runCapability({path:repo},'test');if(!('approvalId' in pending)||!pending.approvalId)throw new Error('missing approval');await approve(pending.approvalId);expect(await runCapability({path:repo},'test')).toMatchObject({status:'complete',executionStatus:'completed',resultStatus:'failed',exitCode:1,summary:{failed:1}});});
  it('invalidates approval when the repository execution definition changes',async()=>{const repo=await repository('node -e "console.log(\'Tests  1 passed\')"');const pending=await runCapability({path:repo},'test');if(!('approvalId' in pending)||!pending.approvalId)throw new Error('missing approval');await approve(pending.approvalId);await writeFile(path.join(repo,'package.json'),JSON.stringify({scripts:{test:'node -e "console.log(\'changed\')"'},devDependencies:{vitest:'1'}}));expect(await runCapability({path:repo},'test')).toMatchObject({status:'approval_required',reason:'execution_definition_changed'});});
  it('does not expose DevBrain control paths to repository code',async()=>{const repo=await repository('node -e "console.log(process.env.DEVBRAIN_HOME||\'control-path-hidden\')"');const pending=await runCapability({path:repo},'test');if(!('approvalId' in pending)||!pending.approvalId)throw new Error('missing approval');await approve(pending.approvalId);const result=await runCapability({path:repo},'test');expect(result).toMatchObject({status:'complete',output:{stdoutTail:expect.stringContaining('control-path-hidden')}});expect('output'in result&&result.output?.stdoutTail).not.toContain(process.env.DEVBRAIN_HOME);});
});
